### PR TITLE
fix yaml property for env_file

### PR DESCRIPTION
**Pull request by J-Zeitler**

### CODE REVIEW

**Comment by J-Zeitler** [comment]
was removing `env_file` properties before, replaceing them with `{}`

**Comment by J-Zeitler** [comment]
however, would like to support type union `string | []string`. could we do that?

with this PR:

works :heavy_check_mark:   
```yaml
        env_file:
            - ./path/to/.myenv
```

fails :x:   
```yaml
        env_file: ./path/to/.myenv
```

**Comment by larsve** [comment]
If I understand you correct, we could just change it's type from `[]string` to `interface{}` (or `any`) and add a comment about expected types (like we have for `Command`), since the docker compose file reference (both version 2 and 3) seems to support either `string` or `[]string` types for `EnvFile`..

**Comment by larsve** [comment]
LGTM

**Review by larsve — APPROVED** [review]

**Pull request merged**
